### ISSUE TITLE
Adjust temperature

### ISSUE THREAD

**Issue by Bl00d-B0b** [klausahrenberg/WThermostatBeca#77]
Hello,

Is it possible to implement temperature adjustments in firmware. as some my thermostats show wrong temperature. 
https://www.youtube.com/watch?v=Eyx_WYHbkGY

it wold be also nice to adjust temperature +/1 0.1 degree, not 0.5, as it's shows in VIDEO.

Ed

**Comment by klausahrenberg** [comment]
> Is it possible to implement temperature adjustments in firmware.

It makes no sense because the thermostat has this temperature correction already, here from the manual
![TempCompensation](https://user-images.githubusercontent.com/26508007/78312545-1f0de980-758f-11ea-9797-5631789890fd.png)
However, it's not possible to modify these settings over Wifi. It's only possible at device.

> it wold be also nice to adjust temperature +/1 0.1 degree, not 0.5

Sorry, this I can not change. This firmware is only the 'Wifi'-Part which is replaced. The original firmware and functions of device can not be modified.

**Comment by Bl00d-B0b** [comment]
Hello,

yes, that's works. +/- 1.0. at least it's OK. maybe you have full table of functions? 

Ed

**Comment by klausahrenberg** [comment]
Here ist a link to the manual

https://www.google.com/url?q=http://upload.sunsky-online.com/res/drivers/HC0002_Manual.pdf&sa=U&ved=2ahUKEwiEsKaaq9LoAhUPzqQKHYetCS0QFjAEegQICRAB&usg=AOvVaw3-q2Mv1LQSUg32_F_RmyNd
